// // // // import type { Metadata } from "next";
// // // // import { Geist, Geist_Mono } from "next/font/google";
// // // // import "./globals.css";

// // // // const geistSans = Geist({
// // // //   variable: "--font-geist-sans",
// // // //   subsets: ["latin"],
// // // // });

// // // // const geistMono = Geist_Mono({
// // // //   variable: "--font-geist-mono",
// // // //   subsets: ["latin"],
// // // // });

// // // // export const metadata: Metadata = {
// // // //   title: "Create Next App",
// // // //   description: "Generated by create next app",
// // // // };

// // // // export default function RootLayout({
// // // //   children,
// // // // }: Readonly<{
// // // //   children: React.ReactNode;
// // // // }>) {
// // // //   return (
// // // //     <html lang="en">
// // // //       <body
// // // //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// // // //       >
// // // //         {children}
// // // //       </body>
// // // //     </html>
// // // //   );
// // // // }



// // // // app/layout.js
// // // import './globals.css'
// // // import Navigation from './components/Navigation'

// // // export const metadata = {
// // //   title: 'Report Generator',
// // //   description: 'Генератор отчетов для мобильных устройств',
// // // }

// // // export default function RootLayout({ children }) {
// // //   return (
// // //     <html lang="ru">
// // //       <body className="bg-gray-50 min-h-screen">
// // //         <div className="max-w-md mx-auto bg-white min-h-screen shadow-lg">
// // //           {children}
// // //           <Navigation />
// // //         </div>
// // //       </body>
// // //     </html>
// // //   )
// // // }


// // // app/layout.js
// // import './globals.css'
// // import Navigation from './components/Navigation'
// // import DebugLogger from './components/DebugLogger'

// // export const metadata = {
// //   title: 'Report Generator',
// //   description: 'Генератор отчетов для мобильных устройств',
// // }

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="ru">
// //       <body className="bg-gray-50 min-h-screen">
// //         <div className="max-w-md mx-auto bg-white min-h-screen shadow-lg">
// //           {children}
// //           <Navigation />
// //           <DebugLogger />
// //         </div>
// //       </body>
// //     </html>
// //   )
// // }



// // app/layout.js
// import './globals.css'
// import Navigation from './components/Navigation'
// import DebugLogger from './components/DebugLogger'
// import TelegramProvider from '../components/TelegramProvider'
// import Script from 'next/script'

// export const metadata = {
//   title: 'Asman AI - Report Generator',
//   description: 'Генератор отчетов для Telegram Web App',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="ru">
//       <head>
//         {/* Telegram Web App Script - загружаем первым */}
//         <Script
//           src="https://telegram.org/js/telegram-web-app.js"
//           strategy="beforeInteractive"
//         />

//         {/* Метатеги для Telegram Web App */}
//         <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
//         <meta name="format-detection" content="telephone=no" />
//         <meta name="msapplication-tap-highlight" content="no" />

//         {/* Цветовая схема для Telegram */}
//         <meta name="theme-color" content="#065f46" />
//         <meta name="color-scheme" content="light dark" />
//       </head>
//       <body className="bg-gray-50 min-h-screen">
//         <TelegramProvider>
//           <div className="max-w-md mx-auto bg-white min-h-screen shadow-lg telegram-webapp">
//             {children}
//             <Navigation />
//             <DebugLogger />
//           </div>
//         </TelegramProvider>
//       </body>
//     </html>
//   )
// }


// app/layout.js
import './globals.css'
import Navigation from './components/Navigation'
import DebugLogger from './components/DebugLogger'
import { TelegramProvider } from './contexts/TelegramContext' // Используем правильный TelegramProvider
import Script from 'next/script'

export const metadata = {
  title: 'Asman AI - Report Generator',
  description: 'Генератор отчетов для Telegram Web App',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <head>
        {/* Telegram Web App Script - загружаем первым */}
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
        />

        {/* Метатеги для Telegram Web App */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="msapplication-tap-highlight" content="no" />

        {/* Цветовая схема для Telegram */}
        <meta name="theme-color" content="#065f46" />
        <meta name="color-scheme" content="light dark" />
      </head>
      <body className="bg-gray-50 min-h-screen">
        <TelegramProvider>
          <div className="max-w-md mx-auto bg-white min-h-screen shadow-lg telegram-webapp">
            {children}
            <Navigation />
            <DebugLogger />
          </div>
        </TelegramProvider>
      </body>
    </html>
  )
}